version: "3"

services:
  # Los servicios se indican en el orden de inicio necesario
  # Por ejemplo, 'mongo' debe iniciarse antes que 'order'.

  # Servicio de MongoDB
  mongo:
    image: xracsolrx/p2gps:db
    deploy:
      replicas: 1 # Escalabilidad del servicio
      resources:
        limits:
          cpus: "0.15"
          memory: 200M
      restart_policy:
        condition: on-failure # Reiniciar el contenedor si falla
    ports:
      - "28017:28017" # Mapeo del puerto del contenedor (derecha) con el host (izquierda)
      - "27017:27017"
    volumes:
      - "db-data:/data/db" # Guardar los cambios del contenedor en local

  # Servicio de Order
  order:
    image: xracsolrx/p2gps:order
    depends_on:
      - "mongo" # El servicio 'order' depende del servicio 'mongo'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"

  # Servicio de Web
  web:
    image: xracsolrx/p2gps:web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 300M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"

volumes:
  db-data:
