name: CI solamente
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4 # Download repository to the runner

      # 2. Set up JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }} # Path for settings.xml file

      #### BUILDS ####
      # 3. Set up Gradle version 2.1
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 2.1

      # 4. Build the Frontend
      - name: Build Frontend
        working-directory: src/Clients
        run: ./gradlew build

      # 5. Upload frontend build artifacts (optional)
      - name: Upload Frontend Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Clients
          path: src/Clients/build/libs

      # 6. Build and Test the Backend
      - name: Build and Test Backend
        working-directory: src/Backend/OrderService
        run: ./gradlew build test
